# Generated by Django 5.0.4 on 2024-05-14 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="category",
            name="tag",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
