# Generated by Django 5.0.4 on 2024-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_listing_timestamp_alter_category_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="listing_pic",
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_pic_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
