# Generated by Django 5.0.4 on 2024-05-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_rename_amount_bid_current_bid_watchlist_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
