# Generated by Django 5.0.4 on 2024-05-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0002_category_user_profile_picture_data_listing_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="listing_pic",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
