# Generated by Django 5.0.4 on 2024-05-28 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_listing_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="amount",
            new_name="current_bid",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
