# Generated by Django 5.0.4 on 2024-06-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_watchlist_status_alter_watchlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="bid_boolen",
            field=models.BooleanField(default=False),
        ),
    ]
